<?php

function hidden_image_captcha_captcha($op, $captcha_type = '', $responce = '') {
  switch ($op) {
    case 'list':
      // only offer image CAPTCHA if possible to generate an image CAPTCHA
      list($font, $errmsg, $errvar) = _image_captcha_get_font();
      if (function_exists('imagejpeg') && $font) {
        return array('Image (hidden)');
      }
      else {
        return array();
      }
    case 'generate':
      if ($captcha_type == 'Image (hidden)') {
        $result = image_captcha_captcha($op, 'Image', $responce);

        $rand = rand();
        $result['form']['captcha_response']['#attributes'] = array('class' => 'c'. $rand);
        $result['form']['captcha_response']['#suffix'] .= '<noscript><style>.c'. $rand .'{ display:block; }</style></noscript><script type="text/javascript">Drupal.behaviors.hidden_captcha = function(){ $("#edit-captcha-response.c'. $rand .'").each(function(){ $(this).attr("value", "'. ($result['solution']) .'"); }); }</script>';
        return $result;
      }
    case 'preprocess':
      // Preprocessing the response for case insensitive validation (see above).
      if ($captcha_type == 'Image (hidden)') {
        return strtolower($responce);
      }
    break;
  }
}

function hidden_image_captcha_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['captcha'])) {
    if ($form['captcha']['captcha_info']['#value']['module'] == 'hidden_image_captcha') {
      $class = $form['captcha']['captcha_widgets']['captcha_response']['#attributes']['class'];
      $form['captcha']['#prefix'] = '<style>.'. $class .'{ display:none; }</style><div class="captcha-wrapper '. $class .'">';
      $form['captcha']['#suffix'] = '</div>';
    }
  }
}