<?php

/**
 * Implementation of hook_init().
 */
function front_page_rss_init() {
  drupal_add_feed(
    url('globalrss.xml', array('absolute' => TRUE, )),
    variable_get('site_name', 'Drupal Ukraine')
  );
}


/**
 * Implementation of hook_block().
 */
function front_page_rss_block($op = 'list', $delta = 0) {
 switch ($op) {
    case 'list':
      return array(
        'front_page_rss' => array('info' => t('Front RSS-icon')),
      );
    case 'view':
      switch ($delta) {
        case 'front_page_rss':
          return array(
            'subject' => t('RSS'),
            'content' => l(
              '<img src="/misc/feed.png"/>', 'globalrss.xml',
              $options = array('html' => TRUE, 'absolute' => TRUE, )
            ),
          );
          break;
      }
      break;
  }
}
